import type { CollectionRun, FlightLog, FlightOccurrence } from '../types';

const now = new Date();
const minutesAgo = (minutes: number) => new Date(now.getTime() - minutes * 60000).toISOString();
const daysAgo = (days: number) => new Date(now.getTime() - days * 86400000).toISOString();

export const demoRuns: CollectionRun[] = [
  {
    id: 'demo-run-1',
    captured_at: minutesAgo(5),
    source: 'arrivals',
    fis_update_time: '20260609 12:55',
    flights_found: 44,
    maldivian_found: 12,
    inserted_logs: 12,
    error: null
  },
  {
    id: 'demo-run-2',
    captured_at: minutesAgo(5),
    source: 'departures',
    fis_update_time: '20260609 12:55',
    flights_found: 39,
    maldivian_found: 10,
    inserted_logs: 10,
    error: null
  }
];

export const demoLogs: FlightLog[] = [
  {
    id: 1,
    captured_at: minutesAgo(5),
    source: 'departures',
    fis_update_time: '20260609 12:55',
    airline_id: 'Q2',
    airline_name: 'MALDIVIAN',
    flight_number: 'Q2106',
    route: 'GAN',
    carrier_type: 'D',
    scheduled_time_text: '13:20',
    estimated_time_text: '13:20',
    scheduled_at: minutesAgo(-20),
    estimated_at: minutesAgo(-20),
    terminal: 'T1',
    gate: '4',
    status: 'On Time',
    is_delayed: false,
    is_cancelled: false,
    delay_minutes: 0,
    occurrence_key: 'demo-1'
  },
  {
    id: 2,
    captured_at: minutesAgo(5),
    source: 'arrivals',
    fis_update_time: '20260609 12:55',
    airline_id: 'Q2',
    airline_name: 'MALDIVIAN',
    flight_number: 'Q2807',
    route: 'HANIMAADHOO',
    carrier_type: 'D',
    scheduled_time_text: '12:40',
    estimated_time_text: '12:55',
    scheduled_at: minutesAgo(20),
    estimated_at: minutesAgo(5),
    terminal: 'T1',
    gate: null,
    status: 'Arrived',
    is_delayed: true,
    is_cancelled: false,
    delay_minutes: 15,
    occurrence_key: 'demo-2'
  },
  {
    id: 3,
    captured_at: minutesAgo(10),
    source: 'departures',
    fis_update_time: '20260609 12:50',
    airline_id: 'Q2',
    airline_name: 'MALDIVIAN',
    flight_number: 'Q2142',
    route: 'KAADEHDHOO',
    carrier_type: 'D',
    scheduled_time_text: '12:30',
    estimated_time_text: '12:30',
    scheduled_at: minutesAgo(35),
    estimated_at: minutesAgo(35),
    terminal: 'T1',
    gate: '2',
    status: 'Departed',
    is_delayed: false,
    is_cancelled: false,
    delay_minutes: 0,
    occurrence_key: 'demo-3'
  },
  {
    id: 4,
    captured_at: minutesAgo(15),
    source: 'arrivals',
    fis_update_time: '20260609 12:45',
    airline_id: 'Q2',
    airline_name: 'MALDIVIAN',
    flight_number: 'Q2701',
    route: 'MAAFARU',
    carrier_type: 'D',
    scheduled_time_text: '12:15',
    estimated_time_text: '12:15',
    scheduled_at: minutesAgo(45),
    estimated_at: minutesAgo(45),
    terminal: 'T1',
    gate: null,
    status: 'Landed',
    is_delayed: false,
    is_cancelled: false,
    delay_minutes: 0,
    occurrence_key: 'demo-4'
  },
  {
    id: 5,
    captured_at: minutesAgo(20),
    source: 'departures',
    fis_update_time: '20260609 12:40',
    airline_id: 'Q2',
    airline_name: 'MALDIVIAN',
    flight_number: 'Q2206',
    route: 'KULHUDHUFFUSHI',
    carrier_type: 'D',
    scheduled_time_text: '12:00',
    estimated_time_text: '12:05',
    scheduled_at: minutesAgo(60),
    estimated_at: minutesAgo(55),
    terminal: 'T1',
    gate: '1',
    status: 'Departed',
    is_delayed: false,
    is_cancelled: false,
    delay_minutes: 5,
    occurrence_key: 'demo-5'
  }
];

export const demoOccurrences: FlightOccurrence[] = [
  {
    occurrence_key: 'old-delay-1',
    first_seen_at: daysAgo(18),
    last_seen_at: daysAgo(18),
    source: 'departures',
    airline_id: 'Q2',
    airline_name: 'MALDIVIAN',
    flight_number: 'Q2118',
    route: 'FUVAHMULAH',
    carrier_type: 'D',
    scheduled_time_text: '09:10',
    estimated_time_text: '10:00',
    scheduled_at: daysAgo(18),
    estimated_at: daysAgo(18),
    terminal: 'T1',
    gate: '3',
    status: 'Delayed',
    was_delayed: true,
    first_delayed_at: daysAgo(18),
    max_delay_minutes: 50,
    was_cancelled: false,
    first_cancelled_at: null
  },
  {
    occurrence_key: 'old-delay-2',
    first_seen_at: daysAgo(8),
    last_seen_at: daysAgo(8),
    source: 'arrivals',
    airline_id: 'Q2',
    airline_name: 'MALDIVIAN',
    flight_number: 'Q2811',
    route: 'GAN',
    carrier_type: 'D',
    scheduled_time_text: '15:20',
    estimated_time_text: '16:05',
    scheduled_at: daysAgo(8),
    estimated_at: daysAgo(8),
    terminal: 'T1',
    gate: null,
    status: 'Delayed',
    was_delayed: true,
    first_delayed_at: daysAgo(8),
    max_delay_minutes: 45,
    was_cancelled: false,
    first_cancelled_at: null
  },
  {
    occurrence_key: 'latest-delay',
    first_seen_at: daysAgo(2.3),
    last_seen_at: daysAgo(2.3),
    source: 'arrivals',
    airline_id: 'Q2',
    airline_name: 'MALDIVIAN',
    flight_number: 'Q2807',
    route: 'HANIMAADHOO',
    carrier_type: 'D',
    scheduled_time_text: '12:40',
    estimated_time_text: '12:55',
    scheduled_at: daysAgo(2.3),
    estimated_at: daysAgo(2.3),
    terminal: 'T1',
    gate: null,
    status: 'Arrived',
    was_delayed: true,
    first_delayed_at: daysAgo(2.3),
    max_delay_minutes: 15,
    was_cancelled: false,
    first_cancelled_at: null
  }
];
