// Regenerates src/lib/seedData.ts — a static snapshot of historical flight occurrences
// (first_seen_at < CUTOFF) so older data needs no runtime query. Live data on/after the
// cutoff is fetched at runtime and concatenated by the app.
//
// Run periodically (e.g. monthly) with a fresh CUTOFF so the live "today-onward" query
// stays small: `node scripts/gen-seed.mjs`
// Uses the public anon key (read-only, safe to commit).
import fs from 'node:fs';

const U = 'https://jhqfednaiehimwkzfqle.supabase.co';
const K = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpocWZlZG5haWVoaW13a3pmcWxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA4MjAyMTMsImV4cCI6MjA5NjM5NjIxM30.WXUsykzYS9WHVFWWfWJIvaVwC4ad9gyyCSUqUj_Z8NU';
// Bump this to the start of "today" (Maldives = UTC+5) whenever you regenerate.
const CUTOFF = '2026-07-13T19:00:00Z';
const SEL = 'occurrence_key,source,route,flight_number,scheduled_at,first_seen_at,was_delayed,first_delayed_at,max_delay_minutes';

const all = [];
for (let off = 0; ; off += 1000) {
  const url = `${U}/rest/v1/flight_occurrences?select=${SEL}&first_seen_at=lt.${CUTOFF}&order=first_seen_at.asc&offset=${off}&limit=1000`;
  const res = await fetch(url, { headers: { apikey: K, Authorization: `Bearer ${K}` } });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const rows = await res.json();
  all.push(...rows);
  if (rows.length < 1000) break;
}

const out = `// AUTO-GENERATED by scripts/gen-seed.mjs — snapshot of historical flight occurrences
// (first_seen_at < SEED_CUTOFF). Older data is baked in so it needs no runtime query;
// live data on/after the cutoff is fetched at runtime and concatenated.
import type { OccurrenceStat } from '../types';

export const SEED_CUTOFF = '${CUTOFF}';

export const seedOccurrences: OccurrenceStat[] = ${JSON.stringify(all)};
`;

fs.writeFileSync(new URL('../src/lib/seedData.ts', import.meta.url), out);
console.log('wrote', all.length, 'occurrences');
